export const navLinks = [
  { path: '/', label: 'Trang chu' },
  { path: '/login', label: 'Dang nhap' },
  { path: '/register', label: 'Dang ky' },
  { path: '/discover-vi', label: 'Kham pha' },
  { path: '/statistics', label: 'Thong ke' },
  { path: '/exercise/combine-words', label: 'Ghep tu' },
]

export const stitchPages = [
  { path: '/landing', title: 'Gioi thieu' },
  { path: '/home-vi', title: 'Trang chu' },
  { path: '/discover', title: 'Kham pha' },
  { path: '/discover-vi', title: 'Kham pha tieng Viet' },
  { path: '/community', title: 'Cong dong' },
  { path: '/profile', title: 'Cap nhat ho so' },
  { path: '/forgot-password', title: 'Doi mat khau' },
  { path: '/register', title: 'Dang ky' },
  { path: '/login-v1', title: 'Dang nhap ban 1' },
  { path: '/login', title: 'Dang nhap ban 2' },
  { path: '/topic-selection', title: 'Lua chon chu de' },
  { path: '/input-test/step-1', title: 'Kiem tra dau vao 1' },
  { path: '/input-test/step-2', title: 'Kiem tra dau vao 2' },
  { path: '/input-test/step-3', title: 'Kiem tra dau vao 3' },
  { path: '/input-test/step-4', title: 'Kiem tra dau vao 4' },
  { path: '/input-test/step-5', title: 'Kiem tra dau vao 5' },
  { path: '/exercise/combine-words', title: 'Ghep tu thanh cau' },
  { path: '/exercise/connect-image-word', title: 'Noi tu voi tranh' },
  { path: '/exercise/sentence-arrange', title: 'Sap xep cau' },
  { path: '/exercise/multiple-choice', title: 'Trac nghiem' },
  { path: '/exercise/flashcard', title: 'Flashcard' },
  { path: '/exercise/rhythm-board', title: 'Bang nhip dieu' },
  { path: '/exercise/pronunciation', title: 'Luyen phat am' },
  { path: '/exercise/podcast', title: 'Trinh phat podcast' },
  { path: '/exercise/ai-conversation', title: 'Hoi thoai AI' },
  { path: '/exercise/dialogue-complete', title: 'Hoan thanh hoi thoai' },
  { path: '/statistics', title: 'Thong ke hoc tap' },
]

